### ISSUE TITLE
Release a version for ubuntu jammy dist

### ISSUE THREAD

**Issue by olleolleolle** [aos/dsf-package#2]
This is the same as #1, but for the `jammy` distribution.

I guess I expected to see `Jammy (22.04)` somewhere in that list:

<img width="1025" alt="bild" src="https://user-images.githubusercontent.com/211/170967047-af870cc1-9b08-41c4-8210-78c389f16d2a.png">

**Comment by aos** [comment]
Hi @olleolleolle - apologies for the wait. I've added it to Jammy. Please give it a few hours to sync with Launchpad!
